"""
Report & Document Generator — PDF reports, briefings, note exports.
Falls back to Markdown .txt if pdfplumber/reportlab not installed.
"""
import json
import os
import re
from datetime import datetime
from pathlib import Path

import config
from tools.registry import register

_REPORTS_DIR = config.MEMORY_DIR / "reports"
_REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def _try_pdf(path: Path, title: str, sections: list[dict]) -> bool:
    """Try to generate a PDF. Returns True on success."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        from reportlab.lib.units import mm

        doc    = SimpleDocTemplate(str(path), pagesize=A4,
                                   topMargin=20*mm, bottomMargin=20*mm,
                                   leftMargin=20*mm, rightMargin=20*mm)
        styles = getSampleStyleSheet()
        cyan   = HexColor("#06b6d4")
        dark   = HexColor("#1e293b")

        title_style = ParagraphStyle("title", parent=styles["Title"],
                                     textColor=cyan, fontSize=20, spaceAfter=8)
        h2_style    = ParagraphStyle("h2", parent=styles["Heading2"],
                                     textColor=dark, fontSize=13, spaceBefore=12, spaceAfter=4)
        body_style  = styles["BodyText"]
        body_style.fontSize = 10; body_style.leading = 14

        story = [
            Paragraph(title, title_style),
            Paragraph(f"Generated by JARVIS · {datetime.now().strftime('%Y-%m-%d %H:%M')}",
                      styles["Italic"]),
            HRFlowable(width="100%", thickness=1, color=cyan, spaceAfter=8),
        ]

        for sec in sections:
            if sec.get("heading"):
                story.append(Paragraph(sec["heading"], h2_style))
            content = sec.get("content","")
            for para in content.split("\n\n"):
                para = para.strip()
                if para:
                    story.append(Paragraph(para.replace("\n","<br/>"), body_style))
                    story.append(Spacer(1, 4))

        doc.build(story)
        return True
    except ImportError:
        return False


def _write_markdown(path: Path, title: str, sections: list[dict]):
    lines = [f"# {title}", f"*Generated by JARVIS · {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n"]
    for sec in sections:
        if sec.get("heading"):
            lines.append(f"\n## {sec['heading']}")
        if sec.get("content"):
            lines.append(sec["content"])
    path.write_text("\n".join(lines))


@register(
    name="generate_report",
    description="Generate a PDF (or Markdown) report from a title and content sections.",
    parameters={"type":"object","properties":{
        "title":   {"type":"string","description":"Report title"},
        "content": {"type":"string","description":"Full report content (Markdown ok)"},
        "open_file":{"type":"boolean","description":"Open file when done (default true)"},
    },"required":["title","content"]},
)
def generate_report(title: str, content: str, open_file: bool = True) -> str:
    slug  = re.sub(r"[^a-z0-9]+", "_", title.lower())[:40]
    ts    = datetime.now().strftime("%Y%m%d_%H%M")
    # Parse content into sections by ## headings
    sections = []
    current  = {"heading": "", "content": ""}
    for line in content.split("\n"):
        if line.startswith("## "):
            if current["content"].strip():
                sections.append(current)
            current = {"heading": line[3:].strip(), "content": ""}
        else:
            current["content"] += line + "\n"
    if current["content"].strip():
        sections.append(current)

    pdf_path = _REPORTS_DIR / f"{ts}_{slug}.pdf"
    md_path  = _REPORTS_DIR / f"{ts}_{slug}.md"

    if _try_pdf(pdf_path, title, sections):
        out_path = pdf_path
        fmt      = "PDF"
    else:
        _write_markdown(md_path, title, sections)
        out_path = md_path
        fmt      = "Markdown"

    if open_file:
        try:
            os.startfile(str(out_path))
        except Exception:
            pass

    return (f"Report '{title}' generated as {fmt}: {out_path.name}\n"
            f"Saved to {out_path}, sir.")


@register(
    name="export_notes_pdf",
    description="Export notes (filtered by tag) to a single PDF/Markdown document.",
    parameters={"type":"object","properties":{
        "tag":  {"type":"string","description":"Filter by tag (optional)"},
        "title":{"type":"string","description":"Document title (optional)"},
    }},
)
def export_notes_pdf(tag: str = "", title: str = "") -> str:
    notes_dir = config.MEMORY_DIR / "notes"
    if not notes_dir.exists():
        return "No notes directory found, sir."
    notes = sorted(notes_dir.glob("*.md"), key=lambda p: p.stat().st_mtime, reverse=True)
    if tag:
        notes = [n for n in notes if tag.lower() in n.read_text().lower()]
    if not notes:
        return f"No notes{' with tag '+tag if tag else ''} found, sir."
    sections = []
    for note in notes:
        text  = note.read_text()
        lines = text.splitlines()
        heading = lines[0].lstrip("# ").strip() if lines else note.stem
        body    = "\n".join(lines[1:]).strip()
        sections.append({"heading": heading, "content": body})
    doc_title = title or f"Notes Export{' — '+tag if tag else ''}"
    content   = "\n\n".join(
        f"## {s['heading']}\n{s['content']}" for s in sections
    )
    return generate_report(doc_title, content, open_file=True)


@register(
    name="generate_daily_briefing_pdf",
    description="Generate a PDF of today's daily briefing (weather, calendar, news, todos).",
    parameters={"type":"object","properties":{}},
)
def generate_daily_briefing_pdf() -> str:
    sections = []
    # Calendar
    try:
        from tools.calendar_tools import list_events
        sections.append({"heading": "📅 Upcoming Events", "content": list_events(3)})
    except Exception as e:
        sections.append({"heading": "Calendar", "content": f"Error: {e}"})
    # Todos
    try:
        from tools.productivity import list_todos
        sections.append({"heading": "✅ Today's Tasks", "content": list_todos("pending")})
    except Exception as e:
        sections.append({"heading": "Tasks", "content": f"Error: {e}"})
    # Weather
    try:
        from tools.weather import get_weather
        sections.append({"heading": "🌤 Weather", "content": get_weather()})
    except Exception as e:
        sections.append({"heading": "Weather", "content": f"Error: {e}"})
    # Habits
    try:
        from tools.productivity import list_habits
        sections.append({"heading": "📋 Habits (7 days)", "content": list_habits(7)})
    except Exception as e:
        pass

    title   = f"JARVIS Daily Briefing — {datetime.now().strftime('%A, %B %d %Y')}"
    content = "\n\n".join(f"## {s['heading']}\n{s['content']}" for s in sections)
    return generate_report(title, content, open_file=True)


@register(
    name="list_reports",
    description="List all generated reports.",
    parameters={"type":"object","properties":{}},
)
def list_reports() -> str:
    reports = sorted(_REPORTS_DIR.glob("*"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not reports:
        return "No reports generated yet, sir."
    return "\n".join(
        f"• {r.name}  [{datetime.fromtimestamp(r.stat().st_mtime).strftime('%b %d %H:%M')}]"
        for r in reports[:20]
    )
